FROM alexsuf/fedora

RUN yum -y install pip
RUN dnf install python3
RUN pip install psycopg2-binary && pip install greenplum-python && pip install pg8000
RUN pip install flask && pip install Dash
RUN pip install numpy && pip install SciPy && pip install pandas && pip install Keras && pip install Matplotlib
RUN pip install apache-airflow && pip install Plotly && pip install Dash
RUN pip install pyspark==3.0.1 py4j==0.10.9
RUN pip install Requests && pip install FastAPI
RUN pip install TensorFlow && pip install Keras 
RUN pip install Scikit-learn && pip install XGBoost && pip install Pygame
RUN pip install Torch
RUN pip install opencv-python
RUN yum -y update

CMD ["/bin/bash"]